### ISSUE TITLE
PHP 5.4 dependency

### ISSUE THREAD

**Issue by mattfff** [lightspeedretail/webstore#673]
We've had a customer running with webstore with auto-updates for over a year without any modification on our end, and their store suddenly started having checkout issues. The reason was due to the short PHP array syntax being used in the latest version of core/protected/views-cities/mail/_customerreceipt.php. The box is Ubuntu 12.04LTS, which is PHP 5.3, which doesn't have short array syntax.

Please either fix the templates to be backwards compatible with 5.3, or fix your auto-updater to be aware of the PHP version installed so it at least stops upgrading and breaking stores with down-level PHP. Your system check script still allows 5.3, so it seems that the templates need to be fixed.

Issue is with 3.3, released October 1st: https://github.com/lightspeedretail/webstore/commit/f46a6003f37d2dfa232e0f4f554395849c8186de

Also, please let your support staff know about this issue so that they don't try to pass blame. They claimed we had made unsupported modifications to core, which was both untrue, and also rather difficult to explain to the customer who was quite frustrated at the time.

**Comment by brandinchiu** [comment]
I've also found that their moving to 5.4 was not handled very well.

**Comment by gabeguz** [comment]
Hi @mattfff @brandinchiu Sorry that this has caused problems for you both.  PHP 5.3 has been end-of-lifed by the PHP project for over 1 year and PHP 5.4 was just end-of-lifed one month ago.  For details please see: http://php.net/supported-versions.php

This is mentioned in the Web Store installation guide: https://github.com/lightspeedretail/webstore/wiki/Installing-3 and on the Web Store requirements page:  http://www.lightspeedpos.com/onsite-help/installation-hosting/.  We could have done a better job of communicating this to our users, and are reviewing how to better handle this type of breaking change in the future.

We currently recommend PHP 5.5 for self hosted installs and do not support PHP 5.3 and below.  

The support team has been aware of this since the change was made.  

I've created a new issue to update the systemcheck.php page to warn about using an unsupported version of php.
