### ISSUE TITLE
Amazon AMW API

### ISSUE THREAD

**Issue by birdawn** [lightspeedretail/webstore#685]
Lightspeed don't upload or update products to AMazon, it seams Amazon change some requirements from his side. From my backoffice I see the queue without transaction ID.

 There are any change to do in the code or any contribution ? Any idea? 

Thanks in advance

Juan

**Comment by ottaz** [comment]
Hi Juan,

We ceased development on the Amazon Integration since version 3.2.9 of Web Store. Amazon does not provide a developer-friendly way of keeping up with their ever changing eco-system which included (but was not limited to) their incredibly diverse category and product requirements list. We have a disclaimer on the [support page](https://www.lightspeedhq.com/webhelp/retail/webstore/en/content/integrating-social-media-with-web-store/integrating-web-store-amazon.html) to this effect.

Because the integration was so difficult to manage, we disabled the option for new users as of 3.2.9.

Truthfully, I would suggest overriding the extension completely and rebuilding it from scratch in your custom folder, or integrating a solution that does not go through the Web Store at all.

My apologies for the bad news.

**Comment by birdawn** [comment]
Hi Kevin,
Thanks for this information, at this point I confuse, I don't known if continue with my technologies. LS offer new webstore with a monthly fee that doesn't seams 100% integrated with LS on site.  Also they offer an API monthly fee with channable company.
At this point, i ask your advice, what is better pay a new development for the API or move to the new system ?

**Comment by ottaz** [comment]
Juan, I don't know how much you are aware of this but Web Store is more or less end of life at this point.

https://www.lightspeedhq.com/webhelp/retail/webstore/en/content/eol_notice.html
https://www.lightspeedhq.com/webhelp/onsite/webstore/en/content/eol_notice.html

Unless you or your clients have strong reasons for needing to stay with it, I would recommend switching to our new solution, eCom. 

Both Retail and Onsite work with eCom but because the Onsite integration is fairly recent, we are onboarding those customers in a more calculating way. I would recommend speaking to a Sales representative. They can help you make the right decision in terms of switching or investing in an outside third party solution, but personally, no outside integration is going to work better for you than the one we've built in house.
